{{- if .Values.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.secretName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "secrets.externalSecrets.secretStoreRef.name is required" .Values.secrets.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "common.secretName" . }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.secrets.externalSecrets.data | nindent 4 }}
{{- end }}
