{{- if .Values.global.imageCredentials.create }}
{{- $name := default (printf "%s-registry" (include "common.fullname" .)) .Values.global.imageCredentials.name }}
{{- $reg := .Values.imageCredentials.registry }}
{{- $user := .Values.imageCredentials.username }}
{{- $pass := .Values.imageCredentials.password }}
{{- $email := .Values.imageCredentials.email }}
{{- $auth := printf "%s:%s" $user $pass | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $reg $user $pass $email $auth | b64enc }}
{{- end }}
