"""The shipped migrations against a live Postgres: they apply, they match the models, and they revert.

The offline suite proves every model table has a revision; only a server can prove the revision
builds the table the model describes. Each run migrates a scratch database to ``heads`` and asks
Alembic's own ``check`` whether autogenerate would still emit anything, which is exactly the drift a
hand-shipped baseline can accumulate against its model.

Runs under the same gate as the other contract suites -- ``RUN_PG_CONTRACT=1`` plus a reachable
``DATABASE_URL`` (``bunx nx run db:test-pg-contract``); skipped otherwise.
"""

import asyncio
import os
import uuid
from collections.abc import Iterator
from pathlib import Path

import db.models  # noqa: F401  (import populates SQLModel.metadata)
import env.db
import pytest
from alembic import command
from alembic.config import Config
from db import metadata
from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import create_async_engine

pytestmark = pytest.mark.skipif(not os.getenv("RUN_PG_CONTRACT"), reason="RUN_PG_CONTRACT is not set")

PROJECT = Path(__file__).resolve().parents[1]


async def _admin(statement: str) -> None:
    engine = create_async_engine(env.db.env.async_database_url, isolation_level="AUTOCOMMIT")
    try:
        async with engine.connect() as connection:
            await connection.execute(text(statement))
    finally:
        await engine.dispose()


async def _admin_on(url: str, statement: str) -> None:
    engine = create_async_engine(url)
    try:
        async with engine.begin() as connection:
            await connection.execute(text(statement))
    finally:
        await engine.dispose()


async def _scalar(url: str, statement: str) -> object:
    engine = create_async_engine(url)
    try:
        async with engine.connect() as connection:
            return await connection.scalar(text(statement))
    finally:
        await engine.dispose()


@pytest.fixture
def scratch(monkeypatch: pytest.MonkeyPatch) -> Iterator[tuple[Config, str]]:
    """An Alembic config pointed at a throwaway database, dropped again on the way out."""
    name = f"migrations_{uuid.uuid4().hex[:12]}"
    asyncio.run(_admin(f'CREATE DATABASE "{name}"'))
    url = make_url(env.db.env.async_database_url).set(database=name).render_as_string(hide_password=False)
    config = Config(str(PROJECT / "alembic.ini"))
    config.set_main_option("script_location", str(PROJECT / "src" / "db" / "migrations"))
    config.set_main_option("prepend_sys_path", str(PROJECT / "src"))
    # env.py reads the URL from settings, not alembic.ini; point that at the scratch database.
    monkeypatch.setattr(env.db.env, "database_url", url)
    try:
        yield config, url
    finally:
        monkeypatch.undo()
        asyncio.run(_admin(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))


def test_the_shipped_migrations_build_exactly_the_model_schema(scratch: tuple[Config, str]) -> None:
    config, url = scratch
    command.upgrade(config, "heads")
    # A table the app does not own, as a library or extension would leave one: autogenerate must not
    # propose dropping it.
    asyncio.run(_admin_on(url, "CREATE TABLE library_owned_probe (id integer PRIMARY KEY)"))

    command.check(config)  # raises AutoGenerateDiffsDetected on any drift


def test_downgrade_to_base_removes_every_model_table(scratch: tuple[Config, str]) -> None:
    config, url = scratch
    command.upgrade(config, "heads")
    command.downgrade(config, "base")

    for table in metadata.tables:
        assert asyncio.run(_scalar(url, f"SELECT to_regclass('public.{table}')")) is None, table
