#!/usr/bin/env bun
/**
 * build-docs.ts — derive the README's capabilities table from the
 * `capabilities/<id>/capability.json` scan, the same source of truth
 * `build-registry.ts` reads. The table is injected between the
 * `<!-- table:start -->` / `<!-- table:end -->` markers so GitHub renders it and
 * it can never drift from the manifests.
 *
 * `--check` runs in `framework-check.yaml` and fails the PR on a stale table, the
 * same contract `registry:check` follows.
 *
 *   bun scripts/registry/build-docs.ts          # rewrite README.md between the markers
 *   bun scripts/registry/build-docs.ts --check  # fail if the committed table is stale
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { $ } from "bun";

import {
  type CapabilityIdentity,
  localCapabilityId,
  resolveCapabilityRef,
} from "../shared/capability-identity";
import { type CapabilityManifest, readManifests } from "../shared/manifests";

const root = process.cwd();
const README_PATH = join(root, "README.md");

const TABLE_START = "<!-- table:start -->";
const TABLE_END = "<!-- table:end -->";

const GENERATED_NOTE =
  "<!-- Generated by `bun run docs:build` from capabilities/*/capability.json. Do not edit by hand. -->";

/** Order for display: by `metadata.weight` (the picker's ordering), then local `kind/id`. */
function byWeightThenId(a: CapabilityManifest, b: CapabilityManifest): number {
  const byWeight = (a.metadata?.weight ?? 0) - (b.metadata?.weight ?? 0);
  if (byWeight !== 0) return byWeight;
  return localCapabilityId(a).localeCompare(localCapabilityId(b));
}

/**
 * A GitHub-flavoured Markdown table with minimal, single-space cells. `oxfmt`
 * re-pads every column to its display width when `buildReadme` formats the
 * README, so this deliberately does not align columns itself.
 */
function renderGfmTable(headers: string[], rows: string[][]): string {
  const separator = headers.map(() => "---");
  return [headers, separator, ...rows].map((cells) => `| ${cells.join(" | ")} |`).join("\n");
}

/** The capabilities table, one row per capability in display order. */
function renderTable(manifests: CapabilityManifest[], registryId: string): string {
  const candidates: CapabilityIdentity[] = manifests.map(({ kind, id }) => ({ kind, id }));
  const rows = manifests.toSorted(byWeightThenId).map((m) => {
    const description = m.description;
    if (!description) {
      throw new Error(
        `capability \`${localCapabilityId(m)}\` has no \`description\`; add one for the README table.`,
      );
    }
    const deps = m.dependencies ?? [];
    // Resolve every authored dependency against the registry's own capabilities: a bare id must
    // be unambiguous, a `kind/id` must exist locally. resolveCapabilityRef throws on a malformed,
    // missing, or ambiguous reference, naming the input and the candidates.
    for (const dep of deps) resolveCapabilityRef(dep, registryId, candidates);
    const dependsOn = deps.length > 0 ? deps.map((dep) => `\`${dep}\``).join(", ") : "—";
    // The Capability cell is the local `kind/id`: unique within the registry, so a duplicate leaf
    // id across two kinds still renders (and keys) unambiguously. Escape `|` so a description
    // cannot open a new column; `oxfmt` handles the rest.
    return [
      `\`${localCapabilityId(m)}\``,
      `\`${m.kind}\``,
      m.required === true ? "Yes" : "—",
      m.default === true ? "Yes" : "—",
      description.replaceAll("|", "\\|"),
      dependsOn,
    ];
  });
  return renderGfmTable(
    ["Capability", "Kind", "Required", "Default", "What it adds", "Depends on"],
    rows,
  );
}

function renderTableSection(manifests: CapabilityManifest[], registryId: string): string {
  return [TABLE_START, GENERATED_NOTE, "", renderTable(manifests, registryId), "", TABLE_END].join(
    "\n",
  );
}

/** Replace the text between a marker pair with a freshly rendered section. */
function spliceMarker(text: string, start: string, end: string, section: string): string {
  const from = text.indexOf(start);
  const to = text.indexOf(end);
  if (from === -1 || to === -1) {
    throw new Error(
      `README.md is missing the \`${start}\` / \`${end}\` markers; add them where the section should render.`,
    );
  }
  if (to < from) {
    throw new Error(`README.md has \`${end}\` before \`${start}\`; the markers are swapped.`);
  }
  return `${text.slice(0, from)}${section}${text.slice(to + end.length)}`;
}

/**
 * The README with a freshly rendered capabilities table, formatted by `oxfmt` —
 * the same formatter `format:check` runs. Formatting the output here (rather than
 * hand-padding to guess what `oxfmt` wants) is what lets summaries carry any
 * printable text: `oxfmt` owns column widths, so `docs:check` and `format:check`
 * can never disagree about the table.
 */
async function buildReadme(repoRoot: string = process.cwd()): Promise<string> {
  const manifests = readManifests(repoRoot);
  // SAFETY: repo-owned registry.config.json; only the string `id` is read, to qualify references.
  const { id: registryId } = JSON.parse(
    readFileSync(join(repoRoot, "registry.config.json"), "utf8"),
  ) as { id: string };
  const readme = readFileSync(join(repoRoot, "README.md"), "utf8");
  const spliced = spliceMarker(
    readme,
    TABLE_START,
    TABLE_END,
    renderTableSection(manifests, registryId),
  );
  const oxfmt = join(repoRoot, "node_modules", ".bin", "oxfmt");
  return $`${oxfmt} --stdin-filepath README.md < ${new Response(spliced)}`.text();
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  let generated: string;
  try {
    generated = await buildReadme(root);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }

  if (!check) {
    writeFileSync(README_PATH, generated);
    console.log(`Wrote the capabilities table into ${README_PATH}`);
    return;
  }

  const committed = existsSync(README_PATH) ? readFileSync(README_PATH, "utf8") : "";
  if (committed === generated) {
    console.log("README.md capabilities table is up to date.");
    return;
  }

  console.error(
    "README.md capabilities table is stale — run `bun run docs:build` and commit the result.\n",
  );
  const tmp = join(root, ".README.expected.md");
  writeFileSync(tmp, generated);
  try {
    await $`diff -u ${README_PATH} ${tmp}`.nothrow();
  } finally {
    await $`rm -f ${tmp}`.nothrow();
  }
  process.exit(1);
}

// Only run when executed directly. Importing just loads the builder.
if (import.meta.main) {
  await main();
}

export { buildReadme };
