FROM apache/apisix:3.17.0-debian
COPY --chown=1000:1000 deploy/docker/gateway/config.yaml /usr/local/apisix/conf/config.yaml
COPY --chown=1000:1000 deploy/docker/gateway/apisix.yaml /usr/local/apisix/conf/apisix.yaml
USER 1000:1000
EXPOSE 9080
