"""Initial Vespa schema for the search capability.

The collection name must match INGESTION_COLLECTION_NAME and VESPA_APP_NAME must
match the deployed Vespa application name.

Immutability: do not edit this file once deployed. Add 00X_*.py migrations for
schema changes.
"""

import os

from mistralai.search.toolkit.plugins.vespa.app.schemas.app import (
    IndexingMode,
    SearchMode,
)
from mistralai.search.toolkit.plugins.vespa.app.schemas.query_profile import (
    QueryProfile,
)
from mistralai.search.toolkit.plugins.vespa.migration import (
    VespaMigration,
    add_query_profiles,
    create_schema,
    set_app_name,
)
from mistralai.search.toolkit.plugins.vespa.search.ranking_profile import RankingProfile
from vespa.package import QueryField

_COLLECTION = os.environ.get("INGESTION_COLLECTION_NAME", "mistralai_capabilities_search")
_APP_NAME = os.environ.get("VESPA_APP_NAME", "mistralai-capabilities-search")
_YQL_HYBRID = RankingProfile(_COLLECTION).get_yql_select_hybrid(
    embedding_field_names=["content_embedding"],
)


class CreateIndexSchemaMigration(VespaMigration):
    """Create the initial search index schema."""

    def migrate(self) -> None:
        set_app_name(_APP_NAME)
        create_schema(
            name=_COLLECTION,
            mode=SearchMode.INDEX,
            embedding_dimensions=128,
            indexing_mode=IndexingMode.DOCUMENT_PER_CHUNK,
            default_query_profile_name="hybrid-profile",
        )

        add_query_profiles(
            [
                QueryProfile(
                    name="hybrid-search",
                    fields=[
                        QueryField(name="ranking.profile", value="weighted-rank2"),
                        QueryField(name="hits", value=10),
                        QueryField(
                            name="ranking.features.query(bm25_content_weight)",
                            value=0.5,
                        ),
                        QueryField(
                            name="ranking.features.query(match_content_weight)",
                            value=0.5,
                        ),
                        QueryField(
                            name="ranking.features.query(content_embedding_cosine_similarity_score_weight)",
                            value=5.0,
                        ),
                        QueryField(name="yql", value=_YQL_HYBRID),
                    ],
                ),
            ]
        )
